name: 自动构建
on:
  push:
    paths:
      - 'image/**'  # 仅当photos目录有变更时触发 
  workflow_dispatch:
    inputs:
      logLevel:
        description: '手动触发'
        required: true
        default: 'warning'
      tags:
        description: 'Comma separated project tags'
        required: false    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Generate Gallery Page 
        run: |
          # 用脚本动态生成index.html （示例）
          echo '<div class="gallery">' > index.html  
          for img in photos/*; do 
            echo "<img src='$img' alt='${img##*/}'>" >> index.html  
          done 
          echo '</div>' >> index.html  
          # 可替换为更复杂的模板引擎（如Jinja2）
      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
